apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gdgw281zj-python 
  janus-idp.io/tekton: gdgw281zj-python
  backstage.io/kubernetes-id: gdgw281zj-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gdgw281zj-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml